Remove Bias Language from blocky
0xERR0R/blocky pull request #349
Opened 2021-11-21 14:21 UTC by j0sh3rs

The goal of this PR is to address the majority of the findings for bias language removal as identified by [Splunk's bias language linter](https://github.com/splunk/biased-lang-linter), primarily for the usage of whitelist/blacklist within this repo.

In cases where the term `master` was identified, but was associated with a branch or an external link, those were left in place so as not to break existing flows/docs.

In all cases where `blacklist` was found, it was replaced with `denylist`. Similarly for `whitelist` to `allowlist`.

Regardless, I'd just like to say thank you for this project and its mission. I'd been looking for a lower-weight alternative for pihole and have been very happy with my usage of blocky so far!

2021-11-23 07:15 UTC, 0xERR0R commented
Hi, thank you for you work. I'll review the changes today. We can change the documentation, but I would like not to change any configuration / grafana dashboards etc. to avoid breaking of existing user configuration.

2021-11-23 16:12 UTC, kwitsch commented
> We can change the documentation, but I would like not to change any configuration / grafana dashboards etc. to avoid breaking of existing user configuration.

Maybe we could duplicate problematic endpoints and configurations and mark the old ones as deprecated?
Users would get a transition time of some releases to change there setup and the depricated endpoints could be removed later.

2021-11-23 16:37 UTC, 0xERR0R commented
> > We can change the documentation, but I would like not to change any configuration / grafana dashboards etc. to avoid breaking of existing user configuration.
> 
> Maybe we could duplicate problematic endpoints and configurations and mark the old ones as deprecated? Users would get a transition time of some releases to change there setup and the deprecated endpoints could be removed later.

Sure, this would be the way for configuration. For Grafana dashboard, maybe temporary produce metrics with both keys (old and new) and later remove the old one.

2021-11-23 21:25 UTC, 0xERR0R requested changes
It looks almost good, but there are some compiler errors. Please see also my comments.

2021-11-23 21:25 UTC, 0xERR0R commented on metrics/metrics_event_publisher.go
>  		case lists.ListCacheTypeBlacklist:
It should be "ListCacheTypeDenylist"

2021-11-23 21:25 UTC, 0xERR0R commented on metrics/metrics_event_publisher.go
>  		case lists.ListCacheTypeWhitelist:
It should be "ListCacheTypeAllowlist"

2021-11-23 21:25 UTC, 0xERR0R commented on metrics/metrics_event_publisher.go
> +			Name: "blocky_allowlist_cache",
renaming the metric will break existing grafana dashboards. Better here: create new metric with new name and mark "old" as deprecated. Both metrics should count the same value

2021-11-23 21:25 UTC, 0xERR0R commented on server/server_endpoints.go
> -				URL:   "https://htmlpreview.github.io/?https://github.com/0xERR0R/blocky/blob/master/docs/swagger.html",
This link does not exist. This should show to master

2021-11-23 21:25 UTC, 0xERR0R commented on docs/additional_information.md
>  ### Whitelists
Here and line 51 too?

2021-11-29 14:54 UTC, j0sh3rs commented
Hi @0xERR0R -- thanks for your comments, back to work today so I'll review them and make sure CI passes.

Overall, I agree with the approach -- it would be beneficial to duplicate the metrics with some planned deprecation date so as to phase out the language. Having docs updated to use the non-biased language will get new users setup appropriately. Only updating docs and never dropping support for the original language doesn't ensure the overall issue gets addressed

2022-08-16 04:30 UTC, closed without merging