different cpu usage.. (#544)
0xERR0R/blocky pull request #561
Opened 2022-06-10 23:14 UTC by kwitsch

added fqdnOnly to config(default false)
if enabled all non FQDN requests will immediately respond with NXDOMAIN and no further processing will be done

2022-06-10 23:19 UTC, kwitsch commented
idk why race test failed 😕
worked a few minutes ago...

2022-06-11 11:49 UTC, 0xERR0R commented
This race occurs from time to time, but only on github. I opened an issue to track it

2022-06-20 06:28 UTC, 0xERR0R requested changes
Thanks for your work, it looks very good. Please see my comment, the reason should be changed, otherwise we get problems with prometheus due to unlimited set of data

2022-06-20 06:28 UTC, 0xERR0R commented on resolver/fqdn_only_resolver.go
> +			reason := fmt.Sprintf("NOTFQDN (%s)", domainFromQuestion)
Reason is used as a label in prometheus metric (https://github.com/0xERR0R/blocky/blob/e313ef7fe868601b3b3757d41c3677954d0518b2/resolver/metrics_resolver.go#L48), this should be a limited amount of possible values (for example the group name for blocking or the address from upstream resolver). I think it is fine enough just to return "NOTFQDN" here

2022-06-20 11:00 UTC, 0xERR0R approved these changes

2022-06-20 11:02 UTC, merged