[Feature Request] delivery of blocking group as EDNS error(560)
0xERR0R/blocky pull request #611
Opened 2022-07-31 14:20 UTC by kwitsch

#610 already merged in

added new chained resolver which enriches the dns response with EDE data when enabled

2022-08-01 21:00 UTC, 0xERR0R requested changes
Thanks for your work! I tested this feature -> works like a charm. Please check my questions, maybe there is something we can discuss. Would you like to document this feature in `docs/config.yaml` and `docs/configuration.md`?

2022-08-02 16:29 UTC, kwitsch commented on resolver/ede_resolver.go
> +		addExtraReasoning(resp)
Thought it might be useful to have the used upstream resolver included for some debugging scenarios. 🤷‍♂️
Maybe change it to be configurable?

2022-08-02 16:30 UTC, kwitsch commented on config/config.go
> +	EdeEnabled   bool            `yaml:"edeEnabled" default:"false"`
Will change it 👍

2022-08-03 08:54 UTC, 0xERR0R commented on resolver/ede_resolver.go
> +		addExtraReasoning(resp)
I tried it with dig. I get the reason "BLOCKED (ads)" for blocked domains:
```
; <<>> DiG 9.16.1-Ubuntu <<>> @localhost -p 55555 doubleclick.net
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27164
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 0
; OPT=15: 00 0f 42 4c 4f 43 4b 45 44 20 28 61 64 73 29 ("..BLOCKED (ads)")
;; QUESTION SECTION:
;doubleclick.net.               IN      A

;; ANSWER SECTION:
doubleclick.net.        21600   IN      A       0.0.0.0

;; Query time: 4 msec
;; SERVER: ::1#55555(::1)
;; WHEN: Wed Aug 03 08:50:39 UTC 2022
;; MSG SIZE  rcvd: 79
```

but nothing for resolved:
```
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.16.1-Ubuntu <<>> @localhost -p 55555 google.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20091
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             81      IN      A       142.251.36.46

;; ADDITIONAL SECTION:
.                       0       RESERVED0 OPT   15 28 AABSRVNPTFZFRCAodGNwK3VkcDoxLjEuMS4xKQ==

;; Query time: 4 msec
;; SERVER: ::1#55555(::1)
;; WHEN: Wed Aug 03 08:50:55 UTC 2022
;; MSG SIZE  rcvd: 98
```

Is it a problem with dig?

2022-08-03 11:29 UTC, kwitsch commented on resolver/ede_resolver.go
> +		addExtraReasoning(resp)
Sstrange... diden't test this particular case myself and just implemented it acording to the documentation.
I think it isen't woth investing much time into it therfore i will just remove it.

2022-08-05 21:07 UTC, kwitsch commented on config/config.go
> +	EdeEnabled   bool            `yaml:"edeEnabled" default:"false"`
Changed to Ede.Enable

2022-08-05 21:10 UTC, kwitsch commented on resolver/ede_resolver.go
> +		addExtraReasoning(resp)
dns.ExtendedErrorCodeOther is filtered for now as it seams it isen't implemented in tools like dig.

2022-08-05 21:13 UTC, kwitsch commented
> Thanks for your work! I tested this feature -> works like a charm. Please check my questions, maybe there is something we can discuss. Would you like to document this feature in `docs/config.yaml` and `docs/configuration.md`?

Added as requested 😊

2022-08-06 20:29 UTC, 0xERR0R approved these changes

2022-08-06 20:30 UTC, merged